# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_news', '0007_auto_20200129_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='outage',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'reminder_sent'),
        ),
    ]
