# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates field string attributes for Python 3 strings.
    """

    dependencies = [
        ('user_news', '0008_outage_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.TextField(choices=[('WEBINAR', 'Webinar'), ('CONFERENCE', 'Conference'), ('MEETING', 'Meeting'), ('PAPER', 'Paper'), ('POSTER', 'Poster'), ('PRESENTATION', 'Presentation'), ('TUTORIAL', 'Tutorial'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.IntegerField(choices=[(20, 'Informational'), (25, 'Success'), (30, 'Warning'), (40, 'Error')]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='limit_pages',
            field=models.TextField(blank=True, verbose_name='Limit display only to these page paths (one per line)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='schedule_off',
            field=models.DateTimeField(blank=True, verbose_name='scheduled display end'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='schedule_on',
            field=models.DateTimeField(blank=True, verbose_name='scheduled display start'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='end_date',
            field=models.DateTimeField(verbose_name='expected end of outage'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='reminder_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reminder_sent'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='resolved'),
        ),
        migrations.AlterField(
            model_name='outage',
            name='severity',
            field=models.CharField(choices=[('', ''), ('SEV-1', 'SEV-1'), ('SEV-2', 'SEV-2')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='outage',
            name='start_date',
            field=models.DateTimeField(verbose_name='start of outage'),
        ),
    ]
