# Generated by Django 4.2.20 on 2026-08-05 20:35

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('user_news', '0010_update_outage_severity_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=djangocms_text.fields.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=djangocms_text.fields.HTMLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='usernewspluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
