version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
  # Maintain dependencies for Python, supports pip, pipenv, pip-compile, and poetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Node, supports npm and yarn
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
