# Generated by Django 4.2.20 on 2025-08-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('max_lease_length', 'Maximum lease length (seconds)'), ('lease_update_window', 'Lease update window'), ('su_factor', 'SU factor (hourly cost)')], max_length=255)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('flavor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=1024, null=True)),
                ('project_charge_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'unique_together': {('key', 'flavor_id', 'username', 'project_charge_code')},
            },
        ),
    ]
