# Generated by Django 4.2.20 on 2025-08-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configvariable',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='configvariable',
            constraint=models.UniqueConstraint(fields=('key', 'flavor_id', 'username', 'project_charge_code'), name='unique_config_variable'),
        ),
    ]
