# Generated by Django 4.2.20 on 2026-07-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance_service', '0002_alter_configvariable_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configvariable',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configvariable',
            name='key',
            field=models.CharField(choices=[('max_lease_length', 'Maximum lease length (seconds)'), ('lease_update_window', 'Lease update window'), ('su_factor', 'SU factor (hourly cost)'), ('region_end_date', 'Region end date (Unix UTC timestamp)')], max_length=255),
        ),
    ]
