# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 19:56


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(),
        ),
    ]
