# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-29 20:00


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200129_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
