# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 17:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200129_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
