# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-12 20:29


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200212_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='booktitle',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='publisher',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
