# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 21:44
from __future__ import unicode_literals

from django.db import migrations, models

import json

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_add_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
