# Generated by Django 3.2 on 2021-09-21 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_update_invitations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.CharField(max_length=200)),
                ('award', models.CharField(max_length=200, null=True)),
                ('grant_name', models.CharField(max_length=500, null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_funding', to='projects.project')),
            ],
        ),
    ]
