# Generated by Django 3.2 on 2022-08-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0013_add_tag"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="fieldhierarchy",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="fieldhierarchy",
            name="child",
        ),
        migrations.RemoveField(
            model_name="fieldhierarchy",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="project",
            name="field",
        ),
        migrations.AlterField(
            model_name="invitation",
            name="date_expires",
            field=models.DateTimeField(
                default=projects.models.Invitation._generate_expiration
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="email_address",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="email_code",
            field=models.CharField(
                default=projects.models.Invitation._generate_secret,
                editable=False,
                max_length=26,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="user_issued",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Field",
        ),
        migrations.DeleteModel(
            name="FieldHierarchy",
        ),
    ]
