# Generated by Django 3.2 on 2022-10-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_automatically_tagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='approved_with',
            field=models.CharField(choices=[('PUBLICATION', 'Publication'), ('JUSTIFICATION', 'Justification'), ('EMAIL', 'Email')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus_citations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='semantic_scholar_citations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='source',
            field=models.CharField(default='user_reported', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('IMPORTED', 'Imported')], default='SUBMITTED', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='forum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
