# Generated by Django 3.2 on 2023-03-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_add_chameleon_publications_and_pi_aliases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='scopus_citations',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='semantic_scholar_citations',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='source',
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='PublicationSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar')], max_length=30)),
                ('citation_count', models.IntegerField(default=0)),
                ('found_by_algorithm', models.BooleanField(default=False)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='projects.publication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicationsource',
            constraint=models.UniqueConstraint(fields=('publication', 'name'), name='Unique source for a publication'),
        ),
    ]
