# Generated by Django 3.2 on 2023-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_add_chameleon_publications_and_pi_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='google_scholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='google_scholar_citations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='scopus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='semantic_scholar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('IMPORTED', 'Imported'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=30),
        ),
    ]
