# Generated by Django 3.2 on 2023-03-31 17:51

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def migrate_date_to_sources(apps, schema_editor):
    Publication = apps.get_model("projects", "Publication")
    PublicationSource = apps.get_model("projects", "PublicationSource")
    pubs = Publication.objects.all()
    for pub in pubs:
        if pub.status == "IMPORTED":
            # "no reason to use 'IMPORTED' when source name is other than 'user_reported'
            pub.status = Publication.STATUS_APPROVED
        if pub.source == "scopus":
            citation_count = pub.scopus_citations if pub.scopus_citations else 0
        elif pub.source == "semantic_scholar":
            citation_count = (
                pub.semantic_scholar_citations if pub.semantic_scholar_citations else 0
            )
        else:
            citation_count = 0
        if pub.approved_with == "Publication":
            cites_chameleon = True
        else:
            cites_chameleon = False
        pub.sources.get_or_create(
            name=pub.source,
            citation_count=citation_count,
            entry_created_date=pub.entry_created_date,
            is_found_by_algorithm=True,
            cites_chameleon=cites_chameleon,
            acknowledges_chameleon=False,
            approved_with=pub.approved_with,
        )
        pub.reviewed = True
        pub.save()
    return


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_add_chameleon_publications_and_pi_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="publication",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("APPROVED", "Approved"),
                    ("DUPLICATE", "Duplicate"),
                    ("REJECTED", "Rejected"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PublicationSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("user_reported", "User Reported"),
                            ("scopus", "Scopus"),
                            ("semantic_scholar", "Semantic scholar"),
                            ("google_scholar", "Google Scholar"),
                        ],
                        max_length=30,
                    ),
                ),
                ("citation_count", models.IntegerField(default=0)),
                ("entry_created_date", models.DateField(default=timezone.now)),
                ("is_found_by_algorithm", models.BooleanField(default=False)),
                ("cites_chameleon", models.BooleanField(default=False)),
                ("acknowledges_chameleon", models.BooleanField(default=False)),
                (
                    "approved_with",
                    models.CharField(
                        choices=[
                            ("publication", "Publication"),
                            ("justification", "Justification"),
                            ("email", "Email"),
                            ("pending_review", "Review Pending"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="projects.publication",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="publicationsource",
            constraint=models.UniqueConstraint(
                fields=("publication", "name"), name="Unique source for a publication"
            ),
        ),
        migrations.RunPython(migrate_date_to_sources),
        migrations.RemoveField(
            model_name="publication",
            name="approved_with",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="entry_created_date",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="scopus_citations",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="semantic_scholar_citations",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="source",
        ),
    ]
