# Generated by Django 3.2 on 2023-03-29 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20230313_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationsource',
            old_name='found_by_algorithm',
            new_name='is_found_by_algorithm',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='approved_with',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='entry_created_date',
        ),
        migrations.AddField(
            model_name='publication',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationsource',
            name='approved_with',
            field=models.CharField(choices=[('publication', 'Publication'), ('justification', 'Justification'), ('email', 'Email'), ('pending_review', 'Review Pending')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='publicationsource',
            name='entry_created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicationsource',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicationsource',
            name='is_cited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], max_length=30),
        ),
    ]
