# Generated by Django 3.2 on 2023-04-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_publication_sources_with_data_migrationshell'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationDuplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duplicate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of', to='projects.publication')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='projects.publication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publicationduplicate',
            constraint=models.UniqueConstraint(fields=('duplicate', 'original'), name='Unique duplicate to its duplicate of publication'),
        ),
    ]
