# Generated by Django 3.2 on 2024-03-11 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_duplicate_publications'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_su_budget',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
