# Generated by Django 4.2.16 on 2024-12-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0022_remove_joinrequest_join_request_user_link_unique_constraint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='reviewed_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='reviewed_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='submitted_date',
            field=models.DateField(null=True),
        ),
    ]
