# Generated by Django 4.2.20 on 2025-11-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_publication_ticked_id_alter_publication_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationsource',
            name='source_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
