# Generated by Django 4.2.20 on 2025-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_publicationsource_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REFERENCE_ONLY', 'References, does not use Chameleon'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], max_length=30),
        ),
    ]
