# Generated by Django 4.2.20 on 2025-12-11 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_rawpublication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REFERENCE_ONLY', 'References, does not use Chameleon'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], max_length=30),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_pubs', to='projects.project'),
        ),
    ]
