# Generated by Django 4.2.20 on 2025-12-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_alter_publication_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chameleonpublication',
            old_name='ref',
            new_name='semantic_scholar_ref',
        ),
    ]
