# Generated by Django 4.2.20 on 2025-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_rename_ref_chameleonpublication_semantic_scholar_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar')], max_length=50)),
                ('query', models.TextField()),
            ],
        ),
    ]
