# Generated by Django 4.2.20 on 2025-12-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_publicationquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpublication',
            name='chameleon_publications',
            field=models.ManyToManyField(blank=True, help_text='Chameleon publications that cite this source', related_name='raw_publications', to='projects.chameleonpublication'),
        ),
        migrations.AddField(
            model_name='rawpublication',
            name='publication_queries',
            field=models.ManyToManyField(blank=True, help_text='Queries that found this publication', related_name='raw_publications', to='projects.publicationquery'),
        ),
    ]
