# Generated by Django 4.2.20 on 2025-12-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_rawpublication_chameleon_publications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationquery',
            name='source_type',
            field=models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar'), ('science_direct', 'Science Direct')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='name',
            field=models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar'), ('science_direct', 'Science Direct')], max_length=30),
        ),
    ]
