# Generated by Django 4.2.20 on 2025-12-18 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_alter_publicationquery_source_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('organization', models.CharField(choices=[('acm', 'ACM'), ('ieee', 'IEEE'), ('usenix', 'USENIX'), ('springer', 'Springer'), ('elsevier', 'Elsevier'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('forum_type', models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal'), ('workshop', 'Workshop'), ('symposium', 'Symposium'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('country', models.CharField(blank=True, default='', max_length=128)),
                ('source', models.CharField(default='ai', help_text='ai | heuristic | manual', max_length=32)),
                ('source_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ForumAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='projects.forum')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='normalized_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.forum'),
        ),
    ]
