# Generated by Django 4.2.20 on 2025-12-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_forum_forumalias_publication_normalized_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='chameleonpublication',
            name='scopus_ref',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
