# Generated by Django 4.2.20 on 2026-01-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_chameleonpublication_scopus_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chameleonpublication',
            name='openalex_ref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicationquery',
            name='source_type',
            field=models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar'), ('science_direct', 'Science Direct'), ('openalex', 'OpenAlex')], max_length=50),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='name',
            field=models.CharField(choices=[('user_reported', 'User Reported'), ('scopus', 'Scopus'), ('semantic_scholar', 'Semantic scholar'), ('google_scholar', 'Google Scholar'), ('science_direct', 'Science Direct'), ('openalex', 'OpenAlex')], max_length=30),
        ),
    ]
