# Generated by Django 4.2.20 on 2026-01-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0035_chameleonpublication_openalex_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='normalized_forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='projects.forum'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REFERENCE_ONLY', 'References, does not use Chameleon'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted'), ('PRODUCED_BY_CHAMELEON', 'Produced by the Chameleon team')], max_length=30),
        ),
    ]
