# Generated by Django 4.2.20 on 2026-01-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_publication_normalized_forum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_publication', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_pubs', to='projects.project'),
        ),
    ]
