# Generated by Django 4.2.20 on 2026-01-15 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20260115_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='parent_forum',
            field=models.ForeignKey(blank=True, help_text='Parent venue (e.g. conference hosting this workshop)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_forums', to='projects.forum'),
        ),
    ]
