# Generated by Django 4.2.20 on 2026-01-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_forum_parent_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
