# Generated by Django 4.2.20 on 2026-01-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_alter_publication_year_alter_rawpublication_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopus_citation_count', models.IntegerField(default=0)),
                ('semantic_scholar_citation_count', models.IntegerField(default=0)),
                ('scopus_source_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('semantic_scholar_source_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citation', to='projects.publication')),
            ],
        ),
    ]
