# Generated by Django 4.2.20 on 2026-05-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0041_publicationcitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationsource',
            name='approved_with',
            field=models.CharField(blank=True, choices=[('publication', 'Publication'), ('justification', 'Justification'), ('email', 'Email'), ('form_attestation', 'Form Attestation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rawpublication',
            name='approved_with',
            field=models.CharField(blank=True, choices=[('publication', 'Publication'), ('justification', 'Justification'), ('email', 'Email'), ('form_attestation', 'Form Attestation')], max_length=30, null=True),
        ),
    ]
