# Generated by Django 4.2.20 on 2026-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_alter_publicationsource_approved_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawpublication',
            name='audit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
