# Generated by Django 6.1 on 2026-09-03 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_publication_type_choices_openalex'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('proceedings_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='forum',
            name='parent_forum',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='normalized_forum',
        ),
        migrations.AddField(
            model_name='publication',
            name='venue_edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='projects.venueedition'),
        ),
        migrations.CreateModel(
            name='VenueSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('organization', models.CharField(choices=[('acm', 'ACM'), ('ieee', 'IEEE'), ('usenix', 'USENIX'), ('springer', 'Springer'), ('elsevier', 'Elsevier'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('venue_type', models.CharField(choices=[('conference', 'Conference'), ('journal', 'Journal'), ('workshop', 'Workshop'), ('symposium', 'Symposium'), ('preprint_server', 'Preprint Server'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=32)),
                ('source', models.CharField(default='ai', help_text='ai | heuristic | manual', max_length=32)),
                ('source_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_series', models.ForeignKey(blank=True, help_text='For workshops: the conference series that hosts this workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops', to='projects.venueseries')),
            ],
        ),
        migrations.AddField(
            model_name='venueedition',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='projects.venueseries'),
        ),
        migrations.CreateModel(
            name='VenueSeriesAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=512, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='projects.venueseries')),
            ],
        ),
        migrations.DeleteModel(
            name='ForumAlias',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.AlterUniqueTogether(
            name='venueedition',
            unique_together={('series', 'year')},
        ),
    ]
