version: "3.8"
services:
  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: ["celery"]
    command:
      ["-A", "chameleon", "worker", "-l", "INFO", "--concurrency=1", "-B"]
    env_file:
      - .env
    volumes:
      - .:/project
    depends_on:
      - mysql
      - redis
  referenceapi:
    image: docker.chameleoncloud.org/referenceapi:latest
    ports:
      - 127.0.0.1:8891:8000
  redis:
    image: redis:alpine
  mail:
    image: bytemark/smtp
