services:
  portal:
    image: ${DOCKER_IMAGE_LATEST}
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORTAL_PORT}"]
      timeout: 10s
      retries: 3
    env_file:
      - .env
    volumes:
      - .:/project
      - ./media:/media
      - static:/static
      - cache:/cache
    ports:
      - "127.0.0.1:8890:${PORTAL_PORT}"
    entrypoint: ["python3", "manage.py"]
    command: ["runserver", "0.0.0.0:${PORTAL_PORT}"]
    depends_on:
      - mysql
  referenceapi:
    image: ghcr.io/chameleoncloud/reference-api:latest
    ports:
      - "127.0.0.1:8891:8000"
  mysql:
    image: mariadb:10
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:3306:3306"
  redis:
    image: redis:alpine
  celery:
    image: ${DOCKER_IMAGE_LATEST}
    restart: on-failure
    entrypoint: ["celery"]
    command:
      ["-A", "chameleon", "worker", "-l", "INFO", "--concurrency=1", "-B"]
    env_file:
      - .env
    volumes:
      - .:/project
      - cache:/cache
    depends_on:
      - mysql
      - redis
  vue:
    image: node:16.20.2
    command: sh -c 'yarn && yarn serve'
    working_dir: /project
    volumes:
      - .:/project
    ports:
      - "127.0.0.1:9000:9000"
  mail:
    image: mailhog/mailhog:latest
    restart: always
    ports:
    - "127.0.0.1:8025:8025"
  rt:
    image: quay.io/abh/rt:latest
    volumes:
    - ./rt_config/rt_config.pm:/opt/rt/etc/RT_SiteConfig.pm
    - ./rt_config/start.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    command: >
      sh -c "/docker-entrypoint-initdb.d/init-db.sh"
    ports:
    - "127.0.0.1:8892:8892"

volumes:
  static:
  cache:
