version: "3.8"
services:
  portal:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    restart: "no"
    depends_on:
      - mysql
    volumes:
      - .:/project
      - ./media:/media
      - static:/static
    ports:
      - 127.0.0.1:8890:${PORTAL_PORT}
    entrypoint: ["python3", "manage.py"]
    command: ["runserver", "0.0.0.0:${PORTAL_PORT}"]
  vue:
    image: node:lts
    command: sh -c 'yarn && yarn serve'
    working_dir: /project
    volumes:
      - .:/project
    ports:
      - 127.0.0.1:9000:9000
  mysql:
    image: mariadb:10
    restart: "no"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  static:
