[tool.black]
# Set line length explicitly.
# See https://black.readthedocs.io/en/stable/the_black_code_style.html#line-length for more details
line-length = 88
exclude = "/*(migrations|venv)*/"

[tool.poetry]
authors = ["Chameleon Cloud <contact@chameleoncloud.org>"]
description = ""
name = "portal"
version = "0.1.0"

[tool.poetry.dependencies]
Pillow = "^10.0"
PyYAML = "^6.0.2"
bibtexparser = "^1.2"
celery = "~5.6"
django = "^6.1"
django-bootstrap3 = "^24"
django-cms = "~5.1"
django-csp = "^4.0"
django-filer = "^3.5.0"
django-pipeline = "^4.1.0"
django-polymorphic = ">=4.0"
django-sekizai = "^4.1.0"
django-termsandconditions = "^2.1.1"
django-webpack-loader = "^3.1.1"
djangocms-attributes-field = "^4.0.0"
djangocms-column = "^2.1.0"
djangocms-file = "^4.0"
djangocms-frontend = "^2.5.1"
djangocms-link = "^5.0"
djangocms-picture = "^4.1.1"
djangocms-style = "^3.1.0"
djangocms-text = "^0.9.10"
djangocms-video = "^3.1.0"
djangorestframework = "^3.15"
mock = "^5.0"
mozilla-django-oidc = {git = "https://github.com/chameleoncloud/mozilla-django-oidc"}
mysqlclient = "^2.0"
pybliometrics = {git = "https://github.com/pybliometrics-dev/pybliometrics", tag = "4.2"}
pydetex = "~1.0"
reportlab = "^4.0"
pytas = {git = "https://github.com/ChameleonCloud/pytas"}
python = "~3.12"
setuptools = "<82"
python-blazarclient = {git = "https://github.com/ChameleonCloud/python-blazarclient", branch = "chameleoncloud/stable/train"}
python-cinderclient = "^7.2.0"
python-glanceclient = "4.3.2"
python-ironicclient = "5.1.0"
python-keycloak-client = {git = "https://github.com/ChameleonCloud/python-keycloak-client"}
python-keystoneclient = "5.1.0"
python-novaclient = "18.3.0"
python3-openid = "^3.2.0"
redis = "^5.0"
requests = "^2.25.1"
rt = "^2.0.1"
sqlparse = "^0.5.0"
django-recaptcha = "^4.0.0"
uWSGI = "^2.0.19"
jsonpatch = "^1.32"
nltk = "^3.7"
djangocms-snippet = "^3.1.0"
pymemcache = "^4.0.0"
httpx = "~0.28"
openai = "^2.13.0"
magpub = {git = "https://github.com/ChameleonCloud/magpub.git"}

[tool.poetry.group.dev.dependencies]
black = "^25.0"
flake8 = "^7.0"
pycodestyle = "^2.14.0"
pydocstyle = "^6.0"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.2.0"]