# Generated by Django 2.2.2 on 2019-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_initial', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('last_name',),
            },
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.CharField(max_length=100)),
                ('DOI', models.CharField(max_length=50)),
                ('git_repo', models.CharField(max_length=200)),
                ('launchable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='artifacts', to='sharing.Author')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
