# Generated by Django 2.2.2 on 2019-07-08 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='middle_initial',
        ),
    ]
