# Generated by Django 2.2.2 on 2019-07-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_remove_author_middle_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='DOI',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='git_repo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
