# Generated by Django 2.2.2 on 2019-07-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_auto_20190709_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='artifacts', to='sharing.Label'),
        ),
    ]
