# Generated by Django 2.2.2 on 2019-07-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_auto_20190709_1904'),
        ('sharing', '0004_auto_20190709_2202'),
    ]

    operations = [
    ]
