# Generated by Django 2.2.2 on 2019-07-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0006_merge_20190709_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='zenodo_doi',
            new_name='doi',
        ),
    ]
