# Generated by Django 2.2.2 on 2019-07-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_auto_20190709_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='associated_artifacts',
            field=models.ManyToManyField(blank=True, related_name='associated', to='sharing.Artifact'),
        ),
    ]
