# Generated by Django 2.2.2 on 2019-07-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_artifact_associated_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='full name', editable=False, max_length=600),
            preserve_default=False,
        ),
    ]
