# Generated by Django 2.2.2 on 2019-07-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0011_auto_20190712_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(upload_to='sharing/static/images/uploads/'),
        ),
    ]
