# Generated by Django 2.2.2 on 2019-07-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0013_auto_20190712_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(upload_to='sharing/static/sharing/images/'),
        ),
    ]
