# Generated by Django 2.2.2 on 2019-07-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0014_auto_20190715_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sharing/static/sharing/images/'),
        ),
    ]
