# Generated by Django 2.2.2 on 2019-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0015_auto_20190715_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='short_description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
