# Generated by Django 2.2.2 on 2019-08-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0016_auto_20190729_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='zenodo_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
    ]
