# Generated by Django 2.2.2 on 2019-08-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0017_artifact_zenodo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='zenodo_id',
        ),
        migrations.AddField(
            model_name='artifact',
            name='permanent_id',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
    ]
