# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0002_auto_20200601_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProperties',
        ),
    ]
