# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 21:14


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0003_auto_20200616_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='pi_decision_summary',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='pi_eligibility',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='pi_requested_at',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='pi_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='userproperties',
            name='pi_reviewer',
        ),
    ]
