# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-10 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chameleon', '0004_auto_20200710_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='PIEligibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'REQUESTED', b'Requested'), (b'ELIGIBLE', b'Eligible'), (b'INELIGIBLE', b'Ineligible')], default=b'REQUESTED', max_length=10)),
                ('review_date', models.DateTimeField(editable=False, null=True)),
                ('review_summary', models.TextField(blank=True, null=True)),
                ('requestor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PI Eligibility Request',
            },
        ),
    ]
