# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0005_pieligibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproperties',
            options={'verbose_name': 'User Properties', 'verbose_name_plural': 'User Properties'},
        ),
    ]
