# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-20 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0007_auto_20200716_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieligibility',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ELIGIBLE', 'Eligible'), ('INELIGIBLE', 'Ineligible')], default='REQUESTED', max_length=10),
        ),
    ]
