# Generated by Django 4.2.16 on 2024-11-04 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from chameleon.constants import (
    MSI_UNIVERFSITY_LIST,
    UNI_STATE_LIST,
    EPSCOR_STATES,
)

def insert_institutions(apps, schema_editor):
    Institution = apps.get_model("chameleon", "Institution")
    db_alias = schema_editor.connection.alias
    for uni in UNI_STATE_LIST:
        Institution.objects.using(db_alias).create(
            name=uni["name"],
            state=uni["state"],
            minority_serving_institution=uni["name"] in MSI_UNIVERFSITY_LIST,
            epscor_state=uni["state"] in EPSCOR_STATES,
        )

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chameleon', '0009_pieligibility_department_directory_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=100)),
                ('minority_serving_institution', models.BooleanField()),
                ('epscor_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='chameleon.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=500)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='chameleon.institution')),
            ],
        ),
        migrations.RunPython(
            insert_institutions
        )
    ]
