# Generated by Django 4.2.20 on 2025-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0010_institution_userinstitution_institutionalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieligibility',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
