# Generated by Django 4.2.20 on 2025-12-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0012_keycloakuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('r1', 'R1 University'), ('r2', 'R2 University'), ('cc', 'Community College'), ('gov', 'Government'), ('nonprofit', 'Nonprofit'), ('industry', 'Industry'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='source',
            field=models.CharField(choices=[('canonical', 'Canonical list'), ('ai', 'AI generated'), ('manual', 'Manually entered')], default='canonical', max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='source_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='epscor_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='minority_serving_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='institution',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
