# Generated by Django 6.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chameleon', '0015_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='carnegie_classification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='carnegie_full_classification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='institution',
            name='carnegie_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='institution',
            name='control',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private_nonprofit', 'Private Non-profit'), ('private_forprofit', 'Private For-profit')], max_length=20),
        ),
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='US', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='ipeds_unitid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='parent_ror_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='ror_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='website_domain',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
