# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 02:46


from django.db import migrations, models
import django.db.models.deletion
import sharing_portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0002_artifact_ownership_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('doi', models.CharField(blank=True, max_length=50, validators=[sharing_portal.models.validate_zenodo_doi])),
            ],
        ),
        migrations.AddField(
            model_name='artifactversion',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing_portal.Artifact', related_name='artifact_versions'),
        ),
    ]
