# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 02:49
from __future__ import unicode_literals

from django.db import migrations


def create_initial_versions(apps, schema_editor):
    Artifact = apps.get_model('sharing_portal', 'Artifact')

    for artifact in Artifact.objects.all():
        artifact.artifact_versions.create(doi=artifact.doi, created_at=artifact.created_at)
        # Original permanent ID can be used to create the canonical DOI
        # (10.5281/zenodo. is the prefix for non-sandbox zenodo.org DOIs)
        artifact.doi = '10.5281/zenodo.{}'.format(artifact.permanent_id)
        artifact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0003_artifact_versions'),
    ]

    operations = [
        migrations.RunPython(create_initial_versions)
    ]
