# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-13 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0005_remove_permanent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
