# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 16:47


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0007_add_launch_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='title',
        ),
        migrations.AddField(
            model_name='author',
            name='affiliation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
