# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 19:19


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200708_1116'),
        ('sharing_portal', '0012_artifact_sharing_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing_portal.Artifact')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='shared_to_projects',
            field=models.ManyToManyField(through='sharing_portal.ShareTarget', to='projects.Project'),
        ),
    ]
