# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates the deposition_repo choices with Python 3 string values.
    """

    dependencies = [
        ('sharing_portal', '0013_share_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactversion',
            name='deposition_repo',
            field=models.CharField(choices=[('zenodo', 'Zenodo'), ('chameleon', 'Chameleon'), ('git', 'Git')], default='chameleon', max_length=24),
        ),
    ]
