# Generated by Django 3.2 on 2022-03-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0017_artifact_trovi_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daypassrequest',
            name='artifact',
        ),
        migrations.AddField(
            model_name='daypassrequest',
            name='artifact_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='DaypassProject',
            fields=[
                ('artifact_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
