# Generated by Django 3.2 on 2022-03-17 18:14

from django.db import migrations, models
import django.db.models.deletion


def migrate_reproducibility_projects(apps, schema_editor):
    Artifact = apps.get_model('sharing_portal', 'Artifact')
    DaypassProject = apps.get_model('sharing_portal', 'DaypassProject')
    for artifact in Artifact.objects.filter(reproducibility_project__isnull=False):
        # Project nicknames will not be updated (e.g. will show old portal IDs)
        daypass_project = DaypassProject(
            artifact_uuid=artifact.trovi_uuid, project=artifact.reproducibility_project)
        daypass_project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0017_artifact_trovi_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daypassrequest',
            name='artifact',
        ),
        migrations.AddField(
            model_name='daypassrequest',
            name='artifact_uuid',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.CreateModel(
            name='DaypassProject',
            fields=[
                ('artifact_uuid', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.RunPython(migrate_reproducibility_projects),
    ]
