# Generated by Django 3.2 on 2023-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharing_portal", "0018_change_backend_to_trovi"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artifact_uuid", models.UUIDField()),
            ],
        ),
    ]
