# Generated by Django 3.2 on 2023-08-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharing_portal', '0019_featuredartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('reproducible', 'reproducible'), ('chameleon', 'chameleon')], max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('redirect_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtifactBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_uuid', models.CharField(max_length=36, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved'), ('approved', 'deleted')], max_length=50)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('decision_at', models.DateTimeField(null=True)),
                ('decision_summary', models.TextField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing_portal.badge')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
