# Generated by Django 3.2 on 2023-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing_portal', '0021_alter_badge_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifactbadge',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved'), ('deleted', 'deleted')], max_length=50),
        ),
    ]
