# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    """Updates ImageField syntax for later version.
    """

    dependencies = [
        ('appliance_catalog', '0014_auto_20180625_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='appliance_icon',
            field=models.ImageField(blank=True, upload_to='appliance_catalog/icons/'),
        ),
    ]
