# Generated by Django 4.2.16 on 2025-03-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliance_catalog', '0015_appliance_icon_py3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='needs_review',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='project_flagged',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='project_supported',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
