# Generated by Django 4.2.20 on 2026-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliance_catalog', '0016_alter_appliance_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
