# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_requested',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='decision_summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='justification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='su_allocated',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='su_used',
            field=models.FloatField(null=True),
        ),
    ]

