# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='su_used',
            field=models.FloatField(null=True),
        ),
    ]
