# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20200708_1116'),
        ('allocations', '0002_auto_20200528_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='project_charge_code',
        ),
        migrations.AddField(
            model_name='allocation',
            name='project',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.Project'),
            preserve_default=False,
        ),
    ]
