# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0003_auto_20200708_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('inactive', 'expired or overused'), ('active', 'active'), ('pending', 'waiting for review decision'), ('rejected', 'rejected'), ('approved', 'approved but not active')], max_length=50),
        ),
    ]
