# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-14 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0004_auto_20210107_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='status',
            field=models.CharField(choices=[('inactive', 'expired or overused'), ('active', 'active'), ('pending', 'waiting for review decision'), ('waiting', 'collecting more information from the PI'), ('rejected', 'rejected'), ('approved', 'approved but not active')], max_length=50),
        ),
    ]
