# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-07-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0005_add_waiting_status_to_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='expiration_warning_issued',
            field=models.DateTimeField(null=True),
        ),
    ]
