# Generated by Django 3.2 on 2021-12-01 02:52

from django.db import migrations, models


def set_balance_service_version(apps, schema_editor):
    allocation = apps.get_model('allocations', 'Allocation')
    allocation.objects.all().update(balance_service_version=1)


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0007_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='balance_service_version',
            field=models.IntegerField(default=2),
        ),
        migrations.RunPython(set_balance_service_version)
    ]
