# Generated by Django 3.2 on 2024-03-08 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_delete_status_and_approvedwith_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allocations', '0008_allocation_balance_service_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_budget', models.IntegerField(default=0)),
                ('enforced_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectbudgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
