# Generated by Django 4.2.16 on 2024-11-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0009_chargebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='low_allocation_warning_issued',
            field=models.DateTimeField(null=True),
        ),
    ]
