# Generated by Django 4.2.20 on 2025-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0010_allocation_low_allocation_warning_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
