name: build-portal
on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: docker.chameleoncloud.org
          image_name: portal
          pull_image_and_stages: false
          push_image_and_stages: false
