name: build-portal
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build container
        run: make build
      - name: start env for tests
        run: make start
      - name: run migration tests
        run: make migrations
