# From https://black.readthedocs.io/en/stable/github_actions.html
# autoformats committed code with black python autoformatter
name: Test Portal
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: build portal container
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}
      run: make build
    - name: check django migrations
      env:
        DOCKER_IMAGE: docker.chameleoncloud.org/portal:latest
      run: |
        docker run --rm $DOCKER_IMAGE python3 manage.py makemigrations --check

