name: Run Tests

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=${{ env.BRANCH == 'master' }}

      - name: Pull Docker image
        run: docker pull ${{ steps.meta.outputs.tags }}

      - name: Run tests
        run: docker run --rm ${{ steps.meta.outputs.tags }} ./manage.py test